version: '3'
services:
  b8r-api:
    container_name: b8rapi
    image: urvish91/betterhomes-backend:1.0.4
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8080
      - APP_KEY=
      - DB_URI=mongodb+srv://b8r_app:EsM5QXMGzuCzNKvs@cluster0.sbfwcs4.mongodb.net/b8r_home
      - API_PREFIX=/api/v1
      - TIMEZONE=IN
      - SECRET=b8r_home
      - REFRESH_SECRET=b8r_home-testing
      - JWT_EXPIRY=3d
      - HOST_URL=
      - AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - AWS_REGION=${{ secrets.AWS_REGION }}
      - S3_BUCKET_URL=
      - S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
    ports:
      - "8080:8080"